
package inventarios;

import Logica.conexion;
import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
/*
dejamos esto pendiente para los reportes
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
*/

public class frmInventario extends javax.swing.JFrame {

    // Se instancia una conexion de la clase conecta
    conexion con=new conexion();
    // se asigna la conexion a la base de datos con la variable cn
    Connection cn=con.conectar();
    DefaultTableModel modelo;
    int total=0;
    public frmInventario() {
        initComponents();
        this.setLocationRelativeTo(null);
        mostrarTabla();
        inicio();
    }
void mostrarTabla(){
    // desde aqui mandamos a llamar a todos los usuarios y los listamos en la tabla
     // se crea una matriz para almacenar los datos
      total=0;  
      String[] cabecera={"id","Codigo","Nombre","Pieza","Cantidad","Medida","Minimo"};
        // se definen los registros que llevara la tabla
      String[] registros=new String[7];
        // se hace el llamado sql de todos los usuarios
      String sql="SELECT * FROM inventario";
        //establecemos los anchos en pixeles de las columnas
      int[] anchos={0,80,700,250,80,80,80};
        modelo= new DefaultTableModel(null,cabecera);
        
      try {
       
       Statement table;
       table = cn.createStatement();
       ResultSet rs=table.executeQuery(sql);
       while (rs.next()){
           registros[0]=rs.getString("idinventario");
           registros[1]=rs.getString("codigo");
           registros[2]=rs.getString("nombre");
           registros[3]=rs.getString("pieza");
           registros[4]=rs.getString("cantidad");
           registros[5]=rs.getString("medida");
           registros[6]=rs.getString("minimo");
           total++;
           
           modelo.addRow(registros);
           
       }
       tabla.setModel(modelo);
       for (int i=0;i<cabecera.length;i++){
          tabla.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
          tabla.setFont(new java.awt.Font("Tahoma", 0, 12));
       }
       // asignamos la columna 0 para esconderla
       tabla.getColumnModel().getColumn(0).setMaxWidth(0);
       tabla.getColumnModel().getColumn(0).setMinWidth(0);
       tabla.getColumnModel().getColumn(0).setPreferredWidth(0);
       txtTotal.setText(Integer.toString(total));
       }
       catch (SQLException ex){
           System.out.println ("Sin poder ejecutar el query a la tabla");
       }
    
}
void inicio(){
    txtcodigo1.setEnabled(false);
    txtnombre1.setEnabled(false);
    txtpieza1.setEnabled(false);
    txtexistencias1.setEnabled(false);
    cbounidad.setEnabled(false);
    btnEditar.setEnabled(true);
    btnGrabar.setEnabled(false);
    btnActualizar.setEnabled(false);
    btnCancelar.setEnabled(false);
    txtminimo.setEnabled(false);
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtpieza = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtexistencia = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        panelMaterial = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtcodigo1 = new javax.swing.JTextField();
        txtnombre1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtpieza1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtexistencias1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cbounidad = new javax.swing.JComboBox<>();
        txtId = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtminimo = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnGrabar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JLabel();
        btnMenu = new javax.swing.JButton();
        btnImpresion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtrado"));

        jLabel1.setText("Codigo");

        jLabel2.setText("Nombre");

        jLabel3.setText("Pieza");

        jLabel4.setText("Existencias");

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/buscar.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtpieza, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtexistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtpieza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtexistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado"));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelMaterial.setBackground(new java.awt.Color(204, 204, 204));
        panelMaterial.setBorder(javax.swing.BorderFactory.createTitledBorder("Menu Material"));

        jLabel5.setText("Codigo");

        jLabel6.setText("Nombre");

        jLabel7.setText("Pieza");

        jLabel8.setText("Existencias");

        jLabel9.setText("Unidad");

        cbounidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PAR", "PZA", "DM", "ML", "HOJA", "LITRO", "KILO" }));

        txtId.setFont(new java.awt.Font("Lucida Grande", 0, 5)); // NOI18N
        txtId.setText("CVE");

        jLabel11.setText("Minimo");

        javax.swing.GroupLayout panelMaterialLayout = new javax.swing.GroupLayout(panelMaterial);
        panelMaterial.setLayout(panelMaterialLayout);
        panelMaterialLayout.setHorizontalGroup(
            panelMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMaterialLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(txtId))
                .addGap(18, 18, 18)
                .addGroup(panelMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMaterialLayout.createSequentialGroup()
                        .addComponent(txtcodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtnombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelMaterialLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtminimo))
                        .addContainerGap())
                    .addGroup(panelMaterialLayout.createSequentialGroup()
                        .addComponent(txtpieza1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtexistencias1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbounidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        panelMaterialLayout.setVerticalGroup(
            panelMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMaterialLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMaterialLayout.createSequentialGroup()
                        .addComponent(txtId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtcodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(txtnombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelMaterialLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtminimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtpieza1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtexistencias1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(cbounidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Operaciones"));

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/nuevo.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/actualizar.png"))); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/borrar.png"))); // NOI18N
        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/editar.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnGrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/grabar.png"))); // NOI18N
        btnGrabar.setText("Grabar");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(btnBorrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGrabar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(btnNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGrabar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnActualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBorrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar))
        );

        jLabel10.setText("Total de Materiales:");

        txtTotal.setText("0");

        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/inicio.png"))); // NOI18N
        btnMenu.setText("Regresar al menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        btnImpresion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/impresion.png"))); // NOI18N
        btnImpresion.setText("Imprimir Listado");
        btnImpresion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImpresionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelMaterial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnMenu)
                                .addGap(43, 43, 43)
                                .addComponent(btnImpresion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(txtTotal)
                                .addGap(18, 18, 18)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(txtTotal)
                                .addComponent(btnMenu))
                            .addComponent(btnImpresion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        //buscamos producto segun las especificaciones
        total=0;
        String codigo=txtcodigo.getText();
        String nombre=txtnombre.getText();
        String pieza=txtpieza.getText();
        Double existencia;
        if (!txtexistencia.getText().equals("")){
        existencia=Double.parseDouble(txtexistencia.getText());
        }else existencia=0.0;
        String sql;
        //datos en la tabla 
      String[] cabecera={"id","Codigo","Nombre","Pieza","Cantidad","Medida","Minimo"};
        // se definen los registros que llevara la tabla
      String[] registros=new String[7];
        // se hace el llamado sql de todos los usuarios
       if (existencia==0.0){
           sql="SELECT * FROM inventario WHERE "+
               "codigo like '%"+codigo+"%' AND "+
               "nombre like '%"+nombre+"%' AND "+
               "pieza like '%"+pieza+"%'";
           System.out.println (sql);
       }else{
            sql="SELECT * FROM inventario WHERE "+
               "codigo = '"+codigo+"' AND "+
               "nombre like '%"+nombre+"%' AND "+
               "pieza like '%"+pieza+"%' AND "+
               "existencia = "+existencia+"";
            System.out.println (sql);
       }
        int[] anchos={0,80,700,250,80,80,80};
        modelo= new DefaultTableModel(null,cabecera);
        try {
       
       Statement table;
       table = cn.createStatement();
       ResultSet rs=table.executeQuery(sql);
       while (rs.next()){
           registros[0]=rs.getString("idinventario");
           registros[1]=rs.getString("codigo");
           registros[2]=rs.getString("nombre");
           registros[3]=rs.getString("pieza");
           registros[4]=rs.getString("cantidad");
           registros[5]=rs.getString("medida");
           registros[6]=rs.getString("minimo");
           total++;
           
           modelo.addRow(registros);
           
       }
       tabla.setModel(modelo);
       for (int i=0;i<cabecera.length;i++){
          tabla.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
          tabla.setFont(new java.awt.Font("Tahoma", 0, 12));
       }
       txtTotal.setText(Integer.toString(total));
       }
       catch (SQLException ex){
           System.out.println ("Sin poder ejecutar el query a la tabla");
       }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        //Boton nuevo
        btnBuscar.setEnabled(false);
        btnNuevo.setEnabled(false);
        btnGrabar.setEnabled(true);
        btnEditar.setEnabled(false);
        btnActualizar.setEnabled(false);
        btnBorrar.setEnabled(false);
        btnCancelar.setEnabled(true);
        txtcodigo1.setEnabled(true);
        txtnombre1.setEnabled(true);
        txtpieza1.setEnabled(true);
        txtminimo.setEnabled(true);
        txtexistencias1.setEnabled(true);
        cbounidad.setEnabled(true);
        txtexistencias1.setText("0.00");
        txtminimo.setText("0.00");
        
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
       //se cancela todo
       inicio();
       mostrarTabla();
       btnNuevo.setEnabled(true);
       btnBorrar.setEnabled(true);
       btnCancelar.setEnabled(false);
       txtcodigo1.setText("");
       txtnombre1.setText("");
       txtpieza1.setText("");
       txtexistencias1.setText("");
       txtminimo.setText("");
       btnBuscar.setEnabled(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
       //empezamos a grabar un nuevo registro a la bd de Inventarios
       //verificamos que no esten vacios los campos
       if (txtcodigo1.getText().length()==0){
           JOptionPane.showMessageDialog(this,"Falta escribir el Codigo", "Atencion", 1);
       }
       else if (txtnombre1.getText().length()==0){
       JOptionPane.showMessageDialog(this,"Falta escribir el Nombre", "Atencion", 1);
       }
       else if (txtpieza1.getText().length()==0){
       JOptionPane.showMessageDialog(this,"Falta escribir la pieza", "Atencion", 1);
       }
       else if (txtexistencias1.getText().length()==0){
       JOptionPane.showMessageDialog(this,"Falta escribir las existencias iniciales", "Atencion", 1);
       }else{
       // se verifica la informacion
       String medida=cbounidad.getSelectedItem().toString();
       int respuesta=JOptionPane.showConfirmDialog(this, "Se va a introducir la siguiente informacion\nCodigo:"
               +txtcodigo1.getText()+"\nNombre:"
               +txtnombre1.getText()+"\nPieza:"
               +txtpieza1.getText()+" con "
               +txtexistencias1.getText()+" "
               +medida, "Confirmacion", 2);
       //verificamos que informacion se va a agregar y si lo acepta se integra a la BD
        if (respuesta==0){
           //verificamos que el codigo no este repetido
        int contador=0;
        try {
            String checar="SELECT * FROM inventario WHERE codigo='"+txtcodigo1.getText()+"'";
            Statement repetido;
            repetido = cn.createStatement();
            ResultSet buscar=repetido.executeQuery(checar);
            while(buscar.next()){
                contador++;
                JOptionPane.showMessageDialog(null, "Codigo repetido", "Alerta", 0);
            }
        if (contador==0){
              try {
            String unidad = (String) cbounidad.getSelectedItem();
                Double cantidad=0.00;
                Double minimo=0.00;
                  try {
                      cantidad=Double.parseDouble(txtexistencias1.getText());
                      minimo=Double.parseDouble(txtminimo.getText());
                  } catch (Exception e) {
                      JOptionPane.showMessageDialog(this, "Escribe bien la cantidad\nejemplo: 7.32");
                  }
                  
            Statement stmt=cn.createStatement();
            String sql = "INSERT INTO inventario (codigo,nombre,pieza,cantidad,medida,minimo) " +
            "VALUES ('"
                    +txtcodigo1.getText()+"','"+
                    txtnombre1.getText().toUpperCase()+"','"+
                    txtpieza1.getText().toUpperCase()+"',"+
                    cantidad+",'"+
                    medida+"',"+minimo+");"; 
            stmt.executeUpdate(sql);

            stmt.close();
            JOptionPane.showMessageDialog(null, "Producto Correctamente integrado");
            inicio();
            btnNuevo.setEnabled(true);
            btnBuscar.setEnabled(true);
            btnBorrar.setEnabled(true);
            txtcodigo1.setText("");
            txtnombre1.setText("");
            txtpieza1.setText("");
            txtexistencias1.setText("");
            txtminimo.setText("");
            mostrarTabla();
        } catch (SQLException ex) {
            Logger.getLogger(frmInventario.class.getName()).log(Level.SEVERE, null, ex);
        }  
        }
        } catch (SQLException ex) {
            Logger.getLogger(frmInventario.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_btnGrabarActionPerformed
    }
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
       //editando un producto
        int fila = tabla.getSelectedRow();
        
       if (fila>=0){
           String BuscarProducto;
           BuscarProducto = tabla.getValueAt(fila, 1).toString();
           
           try{
            Statement buscar = cn.createStatement();
            ResultSet resultado = buscar.executeQuery( "SELECT * FROM inventario WHERE codigo='"+BuscarProducto+"'" );
            while ( resultado.next() ) {
                txtcodigo1.setText(resultado.getString("codigo"));
                txtnombre1.setText(resultado.getString("nombre"));
                txtpieza1.setText(resultado.getString("pieza"));
                txtexistencias1.setText(String.valueOf(resultado.getDouble("cantidad")));
                txtId.setText(String.valueOf(resultado.getInt("idinventario")));
                txtminimo.setText(String.valueOf(resultado.getDouble("minimo")));
            }
                }
            catch (SQLException ex){
           System.out.println ("Sin poder ejecutar el query a la tabla");
       }
           }
       //aqui reviso que si se pasaron datos a la clave y activo el boton editar;
       if (txtcodigo1.getText().equals("")){
           JOptionPane.showMessageDialog(null,"Selecciona un campo de la Tabla");
       }else{
           btnBuscar.setEnabled(false);
           txtcodigo1.setEnabled(true);
           txtnombre1.setEnabled(true);
           txtpieza1.setEnabled(true);
           txtexistencias1.setEnabled(true);
           cbounidad.setEnabled(true);
           btnNuevo.setEnabled(false);
           btnEditar.setEnabled(false);
           btnActualizar.setEnabled(true);
           btnBorrar.setEnabled(false);
           btnCancelar.setEnabled(true);
           txtminimo.setEnabled(true);
                  
       } 
    
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        //Actualizamos la informacion
        // se verifica la informacion
       String medida=cbounidad.getSelectedItem().toString();
       int respuesta=JOptionPane.showConfirmDialog(this, "Se va a actualizar la siguiente informacion\nCodigo:"
               +txtcodigo1.getText()+"\nNombre:"
               +txtnombre1.getText()+"\nPieza:"
               +txtpieza1.getText()+" con "
               +txtexistencias1.getText()+" "
               +medida, "Confirmacion", 2);
       //verificamos que informacion se va a agregar y si lo acepta se integra a la BD
        if (respuesta==0){
           
          try {
            String unidad = (String) cbounidad.getSelectedItem();
                Double cantidad=0.00;
                Double minimo=0.00;
                try {
                      cantidad=Double.parseDouble(txtexistencias1.getText());
                      minimo=Double.parseDouble(txtminimo.getText());
                  } catch (Exception e) {
                      JOptionPane.showMessageDialog(this, "Escribe bien la cantidad\nejemplo: 7.32");
                  }
                  
            Statement stmt=cn.createStatement();
            String sql = "UPDATE inventario SET codigo='"+txtcodigo1.getText()+"',nombre='"+txtnombre1.getText().toUpperCase()+"',pieza='"+txtpieza1.getText().toUpperCase()+"',cantidad="+cantidad+",medida='"+unidad+"',minimo="+minimo+" WHERE idinventario="+txtId.getText()+";";
            stmt.executeUpdate(sql);
            stmt.close();
            JOptionPane.showMessageDialog(null, "Producto Correctamente actualizado");
            inicio();
            mostrarTabla();
            btnBuscar.setEnabled(true);
            btnNuevo.setEnabled(true);
            btnBorrar.setEnabled(true);
            txtcodigo1.setText("");
            txtnombre1.setText("");
            txtpieza1.setText("");
            txtexistencias1.setText("");
            txtminimo.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(frmInventario.class.getName()).log(Level.SEVERE, null, ex);
        }  
                
        }
                         
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        //Borrado de un producto
        
          //editando un producto
        int fila = tabla.getSelectedRow();
        
       if (fila>=0){
           String BuscarProducto;
           BuscarProducto = tabla.getValueAt(fila, 1).toString();
           String medida=cbounidad.getSelectedItem().toString();
           try{
            Statement buscar = cn.createStatement();
            ResultSet resultado = buscar.executeQuery( "SELECT * FROM inventario WHERE codigo='"+BuscarProducto+"'" );
            while ( resultado.next() ) {
              int respuesta=JOptionPane.showConfirmDialog(this, "Se va a eliminar el siguiente producto\nCodigo:"
               +tabla.getValueAt(fila, 1).toString()+"\nNombre:"
               +tabla.getValueAt(fila, 2).toString()+"\nPieza:"
               +tabla.getValueAt(fila, 3).toString()+" con "
               +tabla.getValueAt(fila, 4).toString()+" "
               +tabla.getValueAt(fila, 5).toString(), "Confirmacion", 2);
              txtcodigo1.setText(tabla.getValueAt(fila,1).toString());
              
       //verificamos que informacion se va a eliminar 
        if (respuesta==0){
            try{
            String sql="DELETE FROM inventario WHERE idinventario="+tabla.getValueAt(fila,0);
            Statement st;
            st=cn.createStatement();
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null,"Producto Eliminado");
            mostrarTabla();
            st.close();
            
            
        }
        catch (Exception ex){
          JOptionPane.showMessageDialog(null,"no se elimino el elemento");
        }
                
            }
            }
            }
            catch (SQLException ex){
           System.out.println ("Sin poder ejecutar el query a la tabla");
       }
           }
       //aqui reviso que si se pasaron datos a la clave y activo el boton editar;
       if (txtcodigo1.getText().equals("")){
           JOptionPane.showMessageDialog(null,"Selecciona un campo de la Tabla");
           txtcodigo1.setText("");
       }else{
           txtcodigo1.setText("");
       }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private Connection connection=new conexion().conectar();
    private void btnImpresionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImpresionActionPerformed
        //Impresion de inventario
        
        Map p=new HashMap();
        JasperReport report;
        JasperPrint print;
        
        try {
              report=JasperCompileManager.compileReport(new File("").getAbsolutePath()+
                      "/src/reportes/rptListadoInventario.jrxml");
              print=JasperFillManager.fillReport(report,p,connection);
              JasperViewer view=new JasperViewer(print,false);
              view.setTitle("Reporte de Inventarios");
              view.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_btnImpresionActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
       Principal frm=new Principal();
       frm.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnMenuActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnImpresion;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cbounidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelMaterial;
    private javax.swing.JTable tabla;
    private javax.swing.JLabel txtId;
    private javax.swing.JLabel txtTotal;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtcodigo1;
    private javax.swing.JTextField txtexistencia;
    private javax.swing.JTextField txtexistencias1;
    private javax.swing.JTextField txtminimo;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtnombre1;
    private javax.swing.JTextField txtpieza;
    private javax.swing.JTextField txtpieza1;
    // End of variables declaration//GEN-END:variables
}
