/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tallerdecalzado;

import Calzado.CalzadoPrincipal;
import Logica.conexion;
import Produccion.OrdenProduccion;
import Produccion.menuProduccion;
import administracion.Administracion;
import inventarios.Principal;
import inventarios.frmInventario;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author MaoRivera
 */
public class Login extends javax.swing.JFrame {
    
    conexion con=new conexion();
    Connection cn=con.conectar();
    
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        ImageIcon img = new ImageIcon("Graficos/icono.png");
        this.setIconImage(img.getImage());
        txtUsuario.requestFocus();
    }

    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Graficos/icono.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtClave = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("CLAVE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, -1, -1));

        txtUsuario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 340, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("USUARIO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, -1));

        txtClave.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 340, -1));

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setText("ACCEDER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 560, 120, 50));

        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/login.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 635, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Acceso
        /*if (txtUsuario.getText().equals("Leonardo")){
            CalzadoPrincipal frm=new CalzadoPrincipal();
           
            frm.setVisible(true);
            frm.setDefaultLookAndFeelDecorated(false);
            this.dispose();
        }else if(txtUsuario.getText().equals("Jaime")){
            Principal frm=new Principal();
            frm.setVisible(true);
            this.dispose();
        }else {
            JOptionPane.showMessageDialog(null, "Escribe bien el usuario");
            txtUsuario.setText("");
        }*/
        boolean acceso = false;
        try {
            String sql = "SELECT * FROM usuario WHERE usuario='" + txtUsuario.getText() + "'";
            Statement st;
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {

                if (txtClave.getText().equals(rs.getString("clave"))) {
                     if (rs.getString("categoria").equals("Administrador")) {
                        JOptionPane.showMessageDialog(null, "Bienvenido Administrador");
                        new Administracion().setVisible(true);
                        this.dispose();
                        acceso = true;

                    } else if (rs.getString("categoria").equals("Inventarios")) {
                        //Se abre el menu de Inventarios
                        JOptionPane.showMessageDialog(null, "Bienvenido al area de Inventarios");
                        new Principal().setVisible(true);
                        this.dispose();
                        acceso = true;
                    } else if (rs.getString("categoria").equals("Calzado")) {
                        //Se abre el menu de Calzado
                        JOptionPane.showMessageDialog(null, "Bienvenido al area de Calzado");
                        new CalzadoPrincipal().setVisible(true);
                        this.dispose();
                        acceso = true;
                    }else if (rs.getString("categoria").equals("Produccion")) {
                        //Se abre el menu de Produccion
                        JOptionPane.showMessageDialog(null, "Bienvenido al area de Producción");
                        new menuProduccion().setVisible(true);
                        this.dispose();
                        acceso = true;

                    }
                   

                }
                
                
                
            }if (acceso==false){
            JOptionPane.showMessageDialog(null, "Usuario no reconocido por el sistema");
                txtClave.setText("");
                txtUsuario.requestFocus();
                txtUsuario.setText("");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
