/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Produccion;

import Logica.conexion;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mao
 */
public class ProcesosProduccion extends javax.swing.JFrame {

    /**
     * Creates new form ProcesosProduccion
     */
    public ProcesosProduccion() {
        initComponents();
        this.setLocationRelativeTo(null);
        mostrarBienvenida();
        tabla();
        btnIntegrar.setEnabled(false);
    }
    Date myDate = new Date();
    String fechaBuscar=new SimpleDateFormat("yyyy-MM-dd").format(myDate);
    // Se crea el modelo para la tabla
    DefaultTableModel modelo;
    DefaultTableModel modelo2;
    conexion con = new conexion();
    Connection cn = con.conectar();
    
    private void tabla() {
        //preparamos la tabla
        String[] cabecera = { "Modelo", "Combinacion", "Plano", "12", "13", "14", "15", "16", "17", "Pares"};
        // se definen los registros que llevara la tabla
        String[] registros = new String[10];
        // se hace el llamado sql de todas las ordenes de la compra
        
        String sql = "SELECT * FROM compra WHERE fecha='" + fechaBuscar + "'";
        //establecemos los anchos en pixeles de las columnas
        int[] anchos = {50, 100, 50, 20, 20, 20, 20, 20, 20, 30};
        modelo = new DefaultTableModel(null, cabecera);
        ImageIcon calzado=null;
        try {
            Statement table;
            table = cn.createStatement();
            ResultSet rs = table.executeQuery(sql);
            while (rs.next()) {
                //codigo de la imagen aqui :)
               
            // Obtenemos la imagen
        
            try {
            String sqlImagen = "SELECT * FROM calzado where articulo='124'";
            Statement verificar;
            verificar = cn.createStatement();
            ResultSet rsImagen = verificar.executeQuery(sqlImagen);
            while (rsImagen.next()) {
            
            //colocamos la imagen
            Blob blob = rs.getBlob("imagen");

                int blobLength = (int) blob.length();

                byte[] blobAsBytes = blob.getBytes(1, blobLength);
                final BufferedImage bufferedImage = ImageIO.read(new ByteArrayInputStream(blobAsBytes));
                
                
            ImageIcon icon = new ImageIcon(bufferedImage);
            Image conversion = icon.getImage();
            Image escala = conversion.getScaledInstance(100, 68, Image.SCALE_SMOOTH);
            calzado = new ImageIcon(escala);
            }
        } catch (SQLException ex) {
            System.out.println("Sin poder ejecutar el query a la tabla1");
        }  catch (IOException ex) {
               Logger.getLogger(OrdenProduccion.class.getName()).log(Level.SEVERE, null, ex);
           }
                
                registros[0] = rs.getString("modelo");
                registros[1] = rs.getString("combinacion");
                registros[2] = rs.getString("plano");
                registros[3] = rs.getString("n12");
                registros[4] = rs.getString("n13");
                registros[5] = rs.getString("n14");
                registros[6] = rs.getString("n15");
                registros[7] = rs.getString("n16");
                registros[8] = rs.getString("n17");
                registros[9] = rs.getString("pares");
                modelo.addRow(registros);

            }
            tablaOrden.setModel(modelo);
            for (int i = 0; i < cabecera.length; i++) {
                tablaOrden.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
                tablaOrden.setFont(new java.awt.Font("Tahoma", 0, 12));
            }
        } catch (SQLException ex) {
            System.out.println("Sin poder ejecutar el query a la tabla");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtBienvenida = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaOrden = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtProceso = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDetalle = new javax.swing.JTextField();
        btnIntegrar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaProcesos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Inicio"));

        txtBienvenida.setText(" ");

        jLabel1.setText("Se tiene programado para hoy");

        jButton2.setText("Salir");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBienvenida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(76, 76, 76)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(2, 2, 2))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBienvenida)
                        .addComponent(jLabel1))
                    .addComponent(jButton2))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Planos"));

        tablaOrden.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Foto", "Modelo", "Comb.", "Plano"
            }
        ));
        jScrollPane1.setViewportView(tablaOrden);

        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Procesos de Produccion"));

        jLabel2.setText("Proceso");

        jLabel3.setText("Detalle");

        btnIntegrar.setText("Integrar paso");
        btnIntegrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntegrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtProceso)
                            .addComponent(txtDetalle)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnIntegrar)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtProceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnIntegrar))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Procesos"));

        tablaProcesos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Plano", "Paso", "Proceso", "Detalle"
            }
        ));
        jScrollPane2.setViewportView(tablaProcesos);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String Plano=null;
    int paso=1;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //creacion de modelo
        //ahora agrego los datos seleccionados de la tabla
        int fila = tablaOrden.getSelectedRow();
        
       if (fila>=0){
           JOptionPane.showMessageDialog(this, "Se inicia proceso de produccion");
           Plano=tablaOrden.getValueAt(fila, 2).toString();
           
           btnIntegrar.setEnabled(true);
           
       }else{
           JOptionPane.showMessageDialog(this, "Selecciona un plano");
       }
           
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnIntegrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntegrarActionPerformed
        try {
            String pasoNumero=Integer.toString(paso);
            //se prepara a insertarlo en la tabla de usuarios   
            Statement insertar=cn.createStatement();
            String sql="INSERT INTO produccion (plano,paso,proceso,detalle,estado,fecha) VALUES ('"+
                    Plano+"','"+
                    pasoNumero+"','"+
                    txtProceso.getText()+"','"+
                    txtDetalle.getText()+"',"
                    + "'Programado','"+fechaBuscar+"')";
            insertar.executeUpdate(sql);
            
            
            
            JOptionPane.showMessageDialog(null,"se ha integrado el proceso");
            paso++;
            mostrarProcesos();
            
            } catch (SQLException ex) {
            Logger.getLogger(ProcesosProduccion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnIntegrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProcesosProduccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProcesosProduccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProcesosProduccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProcesosProduccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProcesosProduccion().setVisible(true);
            }
        });
    }
    private void mostrarProcesos(){
            
        String[] cabecera={"Plano","Paso","Proceso","Detalle"};
        // se definen los registros que llevara la tabla
        String[] registros=new String[4];
        // se hace el llamado sql de todos los usuarios
        String sql="SELECT * FROM produccion";
         int[] anchos = {50, 50, 200, 200};
        modelo2= new DefaultTableModel(null,cabecera);
        
        try {
       
       Statement table;
       table = cn.createStatement();
       ResultSet rs=table.executeQuery(sql);
       while (rs.next()){
           registros[0]=rs.getString("plano");
           registros[1]=rs.getString("paso");
           registros[2]=rs.getString("proceso");
           registros[3]=rs.getString("detalle");
           
           
           modelo2.addRow(registros);
           
       }
       tablaProcesos.setModel(modelo2);
       for (int i = 0; i < cabecera.length; i++) {
                tablaOrden.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
                tablaOrden.setFont(new java.awt.Font("Tahoma", 0, 12));
       
       }
        }catch (SQLException ex){
           System.out.println ("Sin poder ejecutar el query a la tabla");
       }
    }
private void mostrarBienvenida(){
    java.util.Date fecha = new Date();
    System.out.println (fecha);
    Calendar c1 = Calendar.getInstance();
    String dia = Integer.toString(c1.get(Calendar.DATE));
    String mes = Integer.toString(c1.get(Calendar.MONTH));
    String annio = Integer.toString(c1.get(Calendar.YEAR));
    System.out.println(dia);
    System.out.println(mes);
    System.out.println(annio);
    String Mes=null;
    switch (mes){
        case "0": Mes="Enero";
        break;
        
        case "1": Mes="Febrero";
        break;
        
        case "2": Mes="Marzo";
        break;
        
        case "3": Mes="Abril";
        break;
        
        case "4": Mes="Mayo";
        break;
        
        case "5": Mes="Junio";
        break;
        
        case "6": Mes="Julio";
        break;
        
        case "7": Mes="Agosto";
        break;
        
        case "8": Mes="Septiembre";
        break;
        
        case "9": Mes="Octubre";
        break;
        
        case "10": Mes="Noviembre";
        break;
        
        case "11": Mes="Diciembre";
        break;       
    }
    txtBienvenida.setText("Bienvenido hoy es "+dia+" del mes de "+Mes+" del año de "+annio);
    
    
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIntegrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaOrden;
    private javax.swing.JTable tablaProcesos;
    private javax.swing.JLabel txtBienvenida;
    private javax.swing.JTextField txtDetalle;
    private javax.swing.JTextField txtProceso;
    // End of variables declaration//GEN-END:variables
}
